# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2305b8095fc3fc28276cda2d62cd60b23d44e9c280759fd631a36fe3d79c50306759fc3220a37e9cccbacb58c0f143afa729e424be9ca546127755fd0338e54

test:
  secret_key_base: 097a1d5b2c9e2b99ab4d044bf979aa5446d2ab6017a1364717398e8f3d1857a6ef4a6df04f2ad9629ef8921bf0ba1f491fbfb45e07d1c33e7b032b7570f77464

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
